#nullable enable
using UnityEngine;

namespace CoD.Core
{
    /// <summary>
    /// Plays the arena's room tone: one 2D bed plus the placed loops in
    /// <see cref="AmbienceConfig"/>. It builds its sources once, fades them up,
    /// and then switches itself off.
    ///
    /// WHY IT CREATES ITS OWN AudioSources INSTEAD OF TAKING SERIALIZED ONES.
    /// The arena scene is GENERATED by GreyBoxBuilder and re-generated whenever
    /// the geometry moves. An emitter hand-placed in that scene is an emitter one
    /// rebuild away from being gone, silently, with the config still listing it —
    /// which is the worst of both worlds, because the asset would say the sound
    /// exists. Building from the config means the asset is the single source of
    /// truth: adding a hum near the shop is a row in an asset, not a scene edit,
    /// and the only thing anybody wires into the scene is this component and its
    /// config reference.
    ///
    /// WHY THIS IS NOT A POOL VIOLATION. The project's rule is that everything
    /// which SPAWNS goes through ObjectPool, and the disaster behind that rule is
    /// per-frame Instantiate/Destroy churn during a wave. These objects are
    /// created once in Awake, live for the whole scene, and are never destroyed
    /// or recycled — they are scene furniture, closer to the arena's lights than
    /// to a bullet. Pooling them would add a registration, a prefab and a despawn
    /// path to buy nothing.
    ///
    /// WHY IT DISABLES ITSELF. The only per-frame work here is the fade-in, and
    /// the fade ends. A component that keeps a per-frame callback alive for the
    /// remaining forty minutes of a run to lerp a value that already reached its
    /// target is a cost with no upside, and in a game whose allocation budget is
    /// measured with forty drones alive it is the kind of thing that is only
    /// cheap until there are twenty of them.
    ///
    /// VOLUME IS NOT HANDLED HERE. The player's master volume is applied globally
    /// by SettingsHub through AudioListener.volume, which multiplies every source
    /// in the scene. When a hand-authored AudioMixer finally exists, the migration
    /// is to drop a group into <see cref="AmbienceConfig.outputGroup"/> — this
    /// component already assigns it — and nothing in here changes.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class ArenaAmbience : MonoBehaviour
    {
        [Tooltip("The clips, the volumes and the placements. Nothing is played without one.")]
        [SerializeField] private AmbienceConfig? _config = null;

        /// <summary>
        /// Built in Awake and never resized. Parallel to <see cref="_targets"/> by
        /// index; both are allocated once, which is the only allocation this
        /// component ever makes.
        /// </summary>
        private AudioSource?[] _sources = System.Array.Empty<AudioSource?>();

        /// <summary>The volume each source settles at. The fade multiplies these; it never reads back off the sources.</summary>
        private float[] _targets = System.Array.Empty<float>();

        private float _fade;

        private void Awake()
        {
            Build();

            // Nothing authored, nothing to fade. Reached on every build until
            // somebody adds real clips, so it must be silent rather than noisy.
            if (_sources.Length == 0)
            {
                enabled = false;
                return;
            }

            ApplyFade();
        }

        private void Update()
        {
            if (_config == null) { enabled = false; return; }

            // UNSCALED. The pause menu sets timeScale to 0, and a fade that
            // freezes there leaves the arena half-loud for as long as the menu is
            // open — then jumps when it closes.
            _fade = Mathf.MoveTowards(_fade, 1f,
                Time.unscaledDeltaTime / Mathf.Max(0.01f, _config.fadeInSeconds));

            ApplyFade();

            if (_fade >= 1f) enabled = false;
        }

        private void ApplyFade()
        {
            for (int i = 0; i < _sources.Length; i++)
            {
                AudioSource? source = _sources[i];
                if (source != null) source.volume = _targets[i] * _fade;
            }
        }

        /// <summary>
        /// Creates one source per authored, non-null clip. A null clip is skipped
        /// without a log: it means the row is planned and the WAV has not been
        /// recorded, which is the normal state of this asset today.
        /// </summary>
        private void Build()
        {
            if (_config == null) return;

            int count = _config.roomTone != null ? 1 : 0;
            for (int i = 0; i < _config.emitters.Length; i++)
            {
                AmbienceConfig.Emitter? emitter = _config.emitters[i];
                if (emitter != null && emitter.clip != null) count++;
            }
            if (count == 0) return;

            _sources = new AudioSource?[count];
            _targets = new float[count];
            int next = 0;

            if (_config.roomTone != null)
            {
                AudioSource bed = CreateSource("RoomTone", Vector3.zero);
                bed.clip = _config.roomTone;
                bed.pitch = _config.roomTonePitch;
                // 2D. A bed with any positional component at all drifts as the
                // player crosses the arena, and the whole point of a bed is that
                // it does not move.
                bed.spatialBlend = 0f;
                StartLoop(bed, _config.roomTone);

                _sources[next] = bed;
                _targets[next] = _config.roomToneVolume;
                next++;
            }

            for (int i = 0; i < _config.emitters.Length; i++)
            {
                AmbienceConfig.Emitter? emitter = _config.emitters[i];
                if (emitter == null || emitter.clip == null) continue;

                AudioSource source = CreateSource(emitter.label, emitter.localPosition);
                source.clip = emitter.clip;
                source.pitch = emitter.pitch;
                source.spatialBlend = emitter.spatialBlend;
                source.spread = emitter.spreadDegrees;
                source.rolloffMode = emitter.rolloff;
                source.minDistance = emitter.minDistance;
                source.maxDistance = Mathf.Max(emitter.minDistance + 0.1f, emitter.maxDistance);
                StartLoop(source, emitter.clip);

                _sources[next] = source;
                _targets[next] = emitter.volume;
                next++;
            }
        }

        private AudioSource CreateSource(string sourceName, Vector3 localPosition)
        {
            var holder = new GameObject(sourceName);
            holder.transform.SetParent(transform, false);
            holder.transform.localPosition = localPosition;

            AudioSource source = holder.AddComponent<AudioSource>();
            source.playOnAwake = false;
            source.loop = true;
            // Silent until the fade lifts it. Setting the target volume here and
            // fading from it would put one full-volume frame on screen, which is
            // the click the fade exists to remove.
            source.volume = 0f;
            // Emitters do not move and the listener is a walking player. Doppler
            // on a static loop turns strafing into a pitch warble.
            source.dopplerLevel = 0f;
            if (_config != null) source.outputAudioMixerGroup = _config.outputGroup;
            return source;
        }

        private void StartLoop(AudioSource source, AudioClip clip)
        {
            if (_config != null && _config.randomiseStartTime && clip.length > 0f)
            {
                source.time = Random.Range(0f, clip.length);
            }
            source.Play();
        }
    }
}
