#nullable enable
using UnityEngine;
using UnityEngine.Audio;

namespace CoD.Core
{
    /// <summary>
    /// Everything footsteps are made of, in one asset: how far a stride is, how
    /// loud each gait is, how much the pitch is allowed to wander, and which
    /// clips belong to which floor.
    ///
    /// WHY PITCH JITTER IS A FIRST-CLASS FIELD AND NOT A DETAIL.
    /// A footstep is the most repeated sound in the game — roughly twice a second
    /// for the entire length of a run, which is thousands of plays. Digital audio
    /// repeats a sample EXACTLY, and the ear is extremely good at spotting an
    /// exact repeat: two identical steps in a row stop reading as legs and start
    /// reading as a machine playing a file. Nothing else in this asset can hide
    /// that, and no amount of extra clips fixes it on its own, because a random
    /// pick from four clips still lands on the same clip a quarter of the time.
    /// Jitter the pitch a few percent per step and the same four clips become
    /// hundreds of distinct steps.
    ///
    /// SILENCE IS A VALID STATE. Every clip array here may be empty, and an empty
    /// array is NOT an error — it is "not authored yet". The project ships with
    /// no footstep WAVs on purpose (audio is the sneaky Git-LFS killer at roughly
    /// 10 MB per minute), so <see cref="Footsteps"/> must stay silent and warning-
    /// free until a human drops real clips in. A config that logged an error for
    /// an unauthored clip would produce one error per step, forever.
    ///
    /// THE MIXER IS DELIBERATELY ABSENT. <see cref="outputGroup"/> is null in the
    /// shipped asset because an AudioMixer cannot be generated by any builder —
    /// see docs/systems/audio.md. The field exists so that the day someone hand-
    /// authors a mixer, wiring footsteps into it is one drag in the Inspector
    /// rather than a code change.
    /// </summary>
    [CreateAssetMenu(fileName = "Footsteps_", menuName = "CoD/Footstep Config", order = 70)]
    public sealed class FootstepConfig : ScriptableObject
    {
        /// <summary>
        /// One floor type: how it is recognised, what it sounds like, and how it
        /// colours the gait volumes above.
        ///
        /// A class rather than a struct, unlike WaveConfig.Entry, for one
        /// concrete reason: the compiler here runs at langversion 9, where a
        /// struct may not carry field initialisers. A struct would therefore
        /// deserialise its clip arrays as NULL rather than empty, and every
        /// reader would need a null check that says nothing about intent. A
        /// serializable class gets its initialisers and Unity never puts a null
        /// element in an array of them.
        /// </summary>
        [System.Serializable]
        public sealed class SurfaceSet
        {
            [Tooltip("For humans reading the Inspector. Never matched against anything.")]
            public string label = "Surface";

            [Tooltip("Colliders on any of these layers are this surface. Leave at Nothing to match by physics material only.")]
            public LayerMask layers = 0;

            [Tooltip("The strongest match. A collider carrying this exact PhysicsMaterial is this surface regardless of layer.")]
            public PhysicsMaterial? physicsMaterial = null;

            [Tooltip("Picked at random, never the same one twice running. Empty is fine — it means silence, not an error.")]
            public AudioClip?[] stepClips = System.Array.Empty<AudioClip?>();

            [Tooltip("Played on landing. Empty falls back to stepClips at the landing volume, so a surface only needs these if it lands differently from how it walks.")]
            public AudioClip?[] landClips = System.Array.Empty<AudioClip?>();

            [Tooltip("Multiplies whichever gait volume is in play. Grating is louder than carpet; the gait balance above should not have to be re-tuned per floor.")]
            [Range(0f, 2f)] public float volumeScale = 1f;

            [Tooltip("Multiplies the gait pitch. Small moves read as a different material; large moves read as a different creature.")]
            [Range(0.25f, 4f)] public float pitchScale = 1f;
        }

        [Header("Cadence — a distance accumulator, never a timer")]
        [Tooltip("Metres of ground covered between steps. The SAME at every speed on purpose: sprinting must fire more steps per second because it covers more ground, not because a timer was told to tick faster. A timer gives the same step rate at every speed, which sounds like running on the spot.")]
        [Range(0.2f, 3f)] public float strideLength = 0.85f;

        [Tooltip("Metres/second below which the player counts as standing still. Guards against the accumulator creeping while a wall, a slope or an idle joystick drift produces sub-walking motion.")]
        [Range(0f, 3f)] public float minSpeed = 0.55f;

        [Tooltip("How much of a stride is already banked while standing still, 0-0.95. At 0 the first step after a standstill arrives a full stride late, which reads as the player skating before their feet engage.")]
        [Range(0f, 0.95f)] public float firstStepFraction = 0.55f;

        [Header("Ground probe — ONE ray per step, never per frame")]
        [Tooltip("What counts as floor. Excludes the player's own layer and triggers.")]
        public LayerMask groundMask = ~0;

        [Tooltip("Metres above the player's feet the probe starts. Above the step offset, so a foot half-way up a kerb still finds the kerb.")]
        [Range(0.05f, 2f)] public float probeStartHeight = 0.6f;

        [Tooltip("How far down the probe reaches from its start height. Long enough to survive a frame where the controller is a few centimetres off the floor.")]
        [Range(0.2f, 4f)] public float probeDistance = 1.6f;

        [Header("Gaits — volume and pitch, never spacing")]
        [Range(0f, 1f)] public float walkVolume = 0.55f;
        [Range(0.25f, 4f)] public float walkPitch = 1f;

        [Tooltip("Louder AND slightly lower than walking: a sprinting step is a heavier impact, not a faster one. The extra rate comes free from the accumulator.")]
        [Range(0f, 1f)] public float sprintVolume = 0.85f;
        [Range(0.25f, 4f)] public float sprintPitch = 0.95f;

        [Tooltip("Quiet enough that crouching is audibly a choice. This number is the entire stealth mechanic the game has.")]
        [Range(0f, 1f)] public float crouchVolume = 0.22f;
        [Range(0.25f, 4f)] public float crouchPitch = 1.05f;

        [Header("Jitter — the rule that stops steps sounding like a machine")]
        [Tooltip("Fraction, applied symmetrically. 0.07 means every step lands somewhere in ±7% of its nominal pitch. See the class header: this matters far more than it looks.")]
        [Range(0f, 0.4f)] public float pitchJitter = 0.07f;

        [Tooltip("Fraction, applied symmetrically. Smaller than the pitch jitter — a wandering volume reads as a distance change, which is a lie about where the player is.")]
        [Range(0f, 0.4f)] public float volumeJitter = 0.06f;

        [Header("Landing")]
        [Tooltip("Landing impact below this plays nothing. Stepping off a 20 cm kerb should not thump.")]
        [Range(0f, 1f)] public float landMinImpact = 0.12f;

        [Tooltip("Volume at a FULL-force landing. Scaled down by how soft the landing actually was, so a hop and a drop are different events.")]
        [Range(0f, 1f)] public float landVolume = 0.8f;

        [Tooltip("Never above 1: a landing is heavier than a step, and heavier means lower.")]
        [Range(0.25f, 4f)] public float landPitch = 0.9f;

        [Header("Surfaces")]
        [Tooltip("Ordered. The first entry whose physics material matches wins; failing that, the first whose layer matches; failing that, defaultSurface.")]
        public SurfaceSet[] surfaces = System.Array.Empty<SurfaceSet>();

        [Tooltip("Index used when the probe hits nothing, or hits something no entry claims. The arena is one material today, so this is the entry that does all the work.")]
        [Min(0)] public int defaultSurface = 0;

        [Header("Mixer — not authored yet, on purpose")]
        [Tooltip("Left empty until a human hand-authors an AudioMixer: no builder can generate one. See docs/systems/audio.md. Dropping a group in here is the whole migration.")]
        public AudioMixerGroup? outputGroup = null;

        /// <summary>
        /// The fallback surface index, or -1 when no surface has been authored at
        /// all. Clamped rather than trusted: <see cref="defaultSurface"/> is a
        /// hand-typed index into a hand-edited array, which is exactly the pair
        /// that drifts, and an out-of-range read here would throw once per step.
        /// </summary>
        public int DefaultSurfaceIndex =>
            surfaces.Length == 0 ? -1 : Mathf.Clamp(defaultSurface, 0, surfaces.Length - 1);

        /// <summary>Bounds-checked lookup. Null means "nothing authored for that index", which callers treat as silence.</summary>
        public SurfaceSet? Surface(int index) =>
            index < 0 || index >= surfaces.Length ? null : surfaces[index];

        /// <summary>
        /// Which surface a collider is, most-specific match first.
        ///
        /// PHYSICS MATERIAL BEFORE LAYER, deliberately. The arena is generated and
        /// every piece of it lands on the Default layer — the project has exactly
        /// one usable layer for geometry (Viewmodel is the other, and it is the
        /// gun). Layers are therefore a coarse tool that cannot tell a catwalk
        /// from a floor slab, while a PhysicsMaterial is a per-collider asset a
        /// human can drop onto one object without touching the builder that made
        /// it. Layer matching stays as the cheap bulk case for the day the project
        /// grows layers worth having.
        ///
        /// Reads only <c>sharedMaterial</c> and the layer int, both plain property
        /// reads: no GetComponent, no allocation. This runs once per step, and it
        /// still has no business being expensive.
        /// </summary>
        public int ResolveSurface(Collider? collider)
        {
            if (collider == null) return DefaultSurfaceIndex;

            PhysicsMaterial? material = collider.sharedMaterial;
            if (material != null)
            {
                for (int i = 0; i < surfaces.Length; i++)
                {
                    SurfaceSet? set = surfaces[i];
                    if (set != null && set.physicsMaterial == material) return i;
                }
            }

            int layerBit = 1 << collider.gameObject.layer;
            for (int i = 0; i < surfaces.Length; i++)
            {
                SurfaceSet? set = surfaces[i];
                // A mask of Nothing must never match. Left at 0 it would still
                // pass a naive `(mask & bit) == bit` test for layer 0 in some
                // hand-written forms, and layer 0 is Default — which is every
                // object in the arena.
                if (set != null && set.layers.value != 0 && (set.layers.value & layerBit) != 0) return i;
            }

            return DefaultSurfaceIndex;
        }

#if UNITY_EDITOR
        private void OnValidate()
        {
            // A probe that starts below the floor it is looking for finds nothing
            // and every step falls back to the default surface — silently correct
            // today, because there is only one surface, and silently wrong the
            // moment there are two.
            if (probeDistance < probeStartHeight + 0.1f) probeDistance = probeStartHeight + 0.1f;

            if (surfaces.Length > 0) defaultSurface = Mathf.Clamp(defaultSurface, 0, surfaces.Length - 1);
        }
#endif
    }
}
